apiVersion: v1
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      modelregistry.kubeflow.org/description: Asynchronous job for uploading models
        to Model Registry
    labels:
      app.kubernetes.io/component: async-job
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/name: model-registry-async-job
      app.kubernetes.io/part-of: model-registry
      component: model-registry-job
      modelregistry.kubeflow.org/job-type: async-upload
      modelregistry.kubeflow.org/model-sync-model-artifact-id: ""
      modelregistry.kubeflow.org/model-sync-model-id: ""
      modelregistry.kubeflow.org/model-sync-model-version-id: ""
    name: my-async-upload-job
  spec:
    template:
      metadata:
        labels:
          app.kubernetes.io/component: async-job
          app.kubernetes.io/name: model-registry-async-job
          component: model-registry-job
          modelregistry.kubeflow.org/job-type: async-upload
          modelregistry.kubeflow.org/model-sync-model-artifact-id: ""
          modelregistry.kubeflow.org/model-sync-model-id: ""
          modelregistry.kubeflow.org/model-sync-model-version-id: ""
      spec:
        containers:
        - env:
          - name: MODEL_SYNC_REGISTRY_SERVER_ADDRESS
            value: https://model-registry-rest.apps.rosa.jburdo-rosa-6.019m.p3.openshiftapps.com
          - name: MODEL_SYNC_REGISTRY_PORT
            value: "443"
          - name: MODEL_SYNC_REGISTRY_AUTHOR
            value: jobs-async-upload
          - name: MODEL_SYNC_MODEL_ID
            value: ""
          - name: MODEL_SYNC_MODEL_VERSION_ID
            value: ""
          - name: MODEL_SYNC_MODEL_ARTIFACT_ID
            value: ""
          - name: MODEL_SYNC_SOURCE_TYPE
            value: uri
          - name: MODEL_SYNC_SOURCE_URI
            value: https://huggingface.co/RedHatAI/granite-3.1-8b-instruct-quantized.w4a16/resolve/main/model.safetensors
          - name: MODEL_SYNC_REGISTRY_USER_TOKEN_ENVVAR
            value: KF_PIPELINES_SA_TOKEN_PATH
          - name: KF_PIPELINES_SA_TOKEN_PATH
            value: /var/run/secrets/kubernetes.io/serviceaccount/token
          - name: MODEL_SYNC_DESTINATION_TYPE
            value: oci
          - name: MODEL_SYNC_DESTINATION_OCI_URI
            value: default-route-openshift-image-registry.apps.rosa.jburdo-rosa-6.019m.p3.openshiftapps.com/project3/granite-v1:latest
          - name: MODEL_SYNC_DESTINATION_OCI_REGISTRY
            value: default-route-openshift-image-registry.apps.rosa.jburdo-rosa-6.019m.p3.openshiftapps.com
          - name: MODEL_SYNC_DESTINATION_OCI_USERNAME
            valueFrom:
              secretKeyRef:
                key: username
                name: oci-auth-secret
          - name: MODEL_SYNC_DESTINATION_OCI_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: oci-auth-secret
          - name: MODEL_SYNC_DESTINATION_OCI_ENABLE_TLS_VERIFY
            value: "false"
          - name: MODEL_SYNC_DESTINATION_OCI_BASE_IMAGE
            value: registry.access.redhat.com/ubi8/ubi-minimal:latest
          - name: MODEL_SYNC_MODEL_UPLOAD_INTENT
            value: create_model
          - name: MODEL_SYNC_METADATA_CONFIGMAP_PATH
            value: /etc/model-metadata
          image: quay.io/opendatahub/model-registry-job-async-upload:latest
          name: async-upload
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
          - mountPath: /etc/model-metadata
            name: model-metadata
            readOnly: true
        restartPolicy: Never
        securityContext:
          runAsNonRoot: true
        volumes:
        - configMap:
            name: model-metadata
            optional: true
          name: model-metadata
kind: List
metadata: {}
