apiVersion: v1
items:
- apiVersion: v1
  data:
    ModelArtifact.custom_properties: |
      {}
    ModelArtifact.model_format_name: ""
    ModelArtifact.model_format_version: ""
    ModelArtifact.model_source_class: ""
    ModelArtifact.model_source_group: ""
    ModelArtifact.model_source_id: ""
    ModelArtifact.model_source_kind: ""
    ModelArtifact.model_source_name: ""
    ModelArtifact.name: rh-granite
    ModelArtifact.service_account_name: ""
    ModelArtifact.storage_key: ""
    ModelArtifact.storage_path: ""
    ModelVersion.author: ""
    ModelVersion.custom_properties: |
      {}
    ModelVersion.description: |2+

    ModelVersion.name: v1
    RegisteredModel.custom_properties: |
      {}
    RegisteredModel.description: |2+

    RegisteredModel.name: rh-granite
    RegisteredModel.owner: ""
  kind: ConfigMap
  metadata:
    labels:
      app.kubernetes.io/component: metadata
      app.kubernetes.io/name: model-registry-configmap
      app.kubernetes.io/part-of: model-registry
      modelregistry.kubeflow.org/intent-type: create_model
    name: model-metadata
kind: List
metadata: {}
